# Generated by Django 4.1.7 on 2023-03-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('reqID', models.CharField(max_length=30, primary_key='TRUE', serialize=False)),
                ('date', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=10)),
                ('smoking_status', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('profileimg', models.FileField(upload_to='uploads/')),
                ('emp_mrn', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('pcp', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('docdisc1', models.CharField(max_length=70)),
                ('docdisc2', models.CharField(max_length=70)),
                ('docdisc3', models.CharField(max_length=70)),
                ('RID', models.CharField(max_length=30)),
                ('AuthID', models.CharField(max_length=30)),
                ('services', models.TextField()),
                ('priary_player_disc', models.CharField(max_length=100)),
                ('EDI', models.CharField(max_length=30)),
                ('Assignment', models.CharField(max_length=50)),
                ('force_drop', models.CharField(max_length=10)),
                ('CPT', models.CharField(max_length=30)),
                ('diag', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=60)),
            ],
        ),
    ]
