# Generated by Django 4.1.7 on 2023-03-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='priary_player_disc',
            new_name='primary_player_disc',
        ),
        migrations.AddField(
            model_name='claim',
            name='sAssignment',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='sEDI',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='claim',
            name='secondary_player_disc',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='sforce_drop',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
